# Trigger an n8n workflow to deploy the projet
#
name: Trigger n8n deployement

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      #      - name: APT update
      #        run: apt update
      #      - name: Install WGET
      #        run: apt install wget -y
      - name: Trigger n8n
        run: wget http://n8n.beauget.fr/webhook/b21bd2a3-cc70-47ed-ba3d-97421a39cedc
